const U="https://brqurxainlsteygsqfcu.supabase.co",enc=new TextEncoder();
const e=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const p=v=>String(v||"").split("/").map(encodeURIComponent).join("/");
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"");
async function signature(id,key){const k=await crypto.subtle.importKey("raw",enc.encode(key),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(await crypto.subtle.sign("HMAC",k,enc.encode("history-batch:"+id)))}
async function q(path,key){const r=await fetch(U+"/rest/v1/"+path,{headers:{apikey:key,Authorization:"Bearer "+key}});if(!r.ok)throw Error();return r.json()}
async function photo(path,key){const r=await fetch(U+"/storage/v1/object/sign/task-order-photos/"+p(path),{method:"POST",headers:{apikey:key,Authorization:"Bearer "+key,"Content-Type":"application/json"},body:JSON.stringify({expiresIn:3600})});if(!r.ok)return "";const d=await r.json();return d.signedURL?U+"/storage/v1"+d.signedURL:""}
function m(t){try{return JSON.parse(t.task_content||"{}")||{}}catch{return{type:t.task_content||"count"}}}
function html(t,items,photos){
 const kind=m(t).type||t.task_content||"count",title=kind==="inbound"?"入库记录":kind==="scanorder"?"单号记录":kind==="order"?"扫单记录":"点货记录",single=kind==="scanorder";
 const rows=items.map(x=>"<tr><td>"+e(x.sku)+"</td>"+(single?"":"<td>"+e(x.qty)+"</td>")+"</tr>").join("")||"<tr><td>没有明细</td></tr>";
 const incoming=photos.filter(x=>String(x.order_no||"").startsWith("入库照片")),exceptions=photos.filter(x=>String(x.order_no||"").startsWith("异常：")),other=photos.filter(x=>!String(x.order_no||"").startsWith("入库照片")&&!String(x.order_no||"").startsWith("异常："));
 const gallery=list=>list.length?'<div class="photos">'+list.map(x=>'<a href="'+e(x.url)+'" target="_blank" rel="noopener"><img src="'+e(x.url)+'"><span>'+e(x.order_no||"照片")+'</span></a>').join("")+'</div>':'<div class="muted">没有照片</div>';
 const info='<section class="card"><h1>'+e(title)+'</h1><div class="muted">仓库历史记录</div><div class="meta"><div><b>客户</b>'+e(t.customer_name||"未填写")+'</div><div><b>日期</b>'+e(t.task_date||"")+'</div><div><b>批次 / 任务</b>'+e(t.batch_no||t.task_name||"")+'</div><div><b>总数量</b>'+e(t.total_qty||0)+'</div></div></section>';
 const list='<section class="card"><h2>'+(single?"单号清单":"SKU 数量")+'</h2><table><thead><tr><th>'+(single?"单号":"SKU")+'</th>'+(single?"":"<th>数量</th>")+'</tr></thead><tbody>'+rows+'</tbody></table></section>';
 const photosCard=(heading,list)=>'<section class="card"><h2>'+heading+'</h2>'+gallery(list)+'</section>';
 const body=kind==="inbound"?info+photosCard("入库照片",incoming)+list+photosCard("异常照片及备注",exceptions):info+list+(other.length?photosCard("单号照片",other):"");
 return '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+'</title><style>body{margin:0;background:#f3f4f6;color:#111;font:16px/1.5 -apple-system,BlinkMacSystemFont,"Microsoft YaHei",sans-serif}.wrap{max-width:1000px;margin:auto;padding:18px}.card{background:#fff;border:1px solid #ddd;border-radius:14px;padding:18px;margin-bottom:14px}h1,h2{margin:0 0 10px}h1{font-size:28px}h2{font-size:18px;border-bottom:2px solid #111;padding-bottom:8px}.muted{color:#666}.meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.meta div{background:#f4f4f5;border-radius:9px;padding:10px}.meta b{display:block;font-size:12px;color:#666;margin-bottom:3px}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #ddd;padding:10px}th{background:#111;color:#fff}.photos{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.photos a{display:block}.photos img{display:block;width:100%;height:220px;object-fit:cover;background:#eee;border-radius:8px}.photos span{display:block;font-size:12px;padding:6px 2px;word-break:break-word}@media(max-width:620px){.wrap{padding:10px}.card{padding:14px}.meta{grid-template-columns:1fr}.photos{grid-template-columns:repeat(2,minmax(0,1fr))}.photos img{height:150px}}</style><main class="wrap">'+body+'</main></html>'
}
export default async(req,ctx)=>{const key=Netlify.env.get("SUPABASE_SERVICE_ROLE_KEY"),batch=String(ctx.params?.batchNo||"").trim();if(!key||!batch)return new Response("记录不存在",{status:404});try{const tasks=await q("tasks?select=*&batch_no=eq."+encodeURIComponent(batch)+"&limit=2",key),t=tasks.length===1?tasks[0]:null;if(!t)return new Response("记录不存在或批次号重复",{status:404});const id=t.id;const [items,raw]=await Promise.all([q("task_items?select=sku,qty&task_id=eq."+encodeURIComponent(id)+"&order=sku.asc",key),q("task_order_photos?select=order_no,storage_path&task_id=eq."+encodeURIComponent(id)+"&order=captured_at.asc",key)]);const photos=(await Promise.all(raw.map(async x=>({order_no:x.order_no,url:await photo(x.storage_path,key)})))).filter(x=>x.url);return new Response(html(t,items,photos),{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}})}catch{return new Response("暂时无法读取记录",{status:500})}};
export const config={path:"/history/:batchNo"};